# Generated by Django 5.0 on 2024-04-07 20:58

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Партнер')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('total', models.IntegerField(verbose_name='Сумма договора')),
                ('status', models.BooleanField(default=True, verbose_name='Договор действует')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners', verbose_name='Партнер')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.F('price')), output_field=models.IntegerField(), verbose_name='Сумма')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contracts', verbose_name='Договор')),
            ],
        ),
    ]
