# Generated by Django 5.0 on 2024-04-07 13:58

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
            ],
        ),
        migrations.CreateModel(
            name='Sevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.F('price')), output_field=models.IntegerField())),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contracts')),
            ],
        ),
    ]
