# Generated by Django 5.0 on 2024-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='numbers',
            field=models.CharField(max_length=20),
        ),
    ]
