# Generated by Django 5.0 on 2024-04-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_contracts_numbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sevice',
            new_name='Service',
        ),
    ]
