# Generated by Django 5.0 on 2024-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_sevice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Партнер'),
        ),
    ]
