# Generated by Django 5.0 on 2024-04-07 20:25

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_contracts_date_alter_contracts_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='total',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.F('price')), output_field=models.IntegerField()),
        ),
    ]
