# Generated by Django 5.0 on 2024-04-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_service_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
    ]
