# Generated by Django 5.0 on 2024-04-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_service_amount_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='numbers',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contracts'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]
