# Generated by Django 5.0 on 2024-04-07 20:33

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_alter_contracts_date_alter_contracts_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='numbers',
            field=models.CharField(max_length=20, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Договор действует'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='total',
            field=models.IntegerField(verbose_name='Сумма договора'),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='service',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contracts', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=200, verbose_name='Наименование услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.F('price')), output_field=models.IntegerField(), verbose_name='Сумма'),
        ),
    ]
